// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi4mmzmDcFrazmy_Oko1ONluqP9jynWtg',
    appId: '1:83054607917:android:c58da2c8d174c141c2c2a4',
    messagingSenderId: '83054607917',
    projectId: 'renew-social-1290a',
    storageBucket: 'renew-social-1290a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzWVfBB2YcdRuyNh6b3ZKmuGbaZtvhngc',
    appId: '1:83054607917:ios:49a834e78e6b9ceec2c2a4',
    messagingSenderId: '83054607917',
    projectId: 'renew-social-1290a',
    storageBucket: 'renew-social-1290a.appspot.com',
    androidClientId: '83054607917-vkbetsgqstrt45i2g7i7d6g99p9c7tn5.apps.googleusercontent.com',
    iosClientId: '83054607917-mpolsv9cukhfvukr3q6mq95b75lcp2u2.apps.googleusercontent.com',
    iosBundleId: 'com.codabee.fluttersocial',
  );
}
